name: Bedwars
version: 0.1
api: 3.0.0-ALPHA11
main: Epic\Bedwars
author: EpicSteve33
OriginalAuthor: BluPlayz
website: http://www.kcmcpe.net
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
